from datetime import date, datetime, timezone

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models import Note, Patient, PatientStatus

SEED_PATIENTS = [
    {
        "first_name": "James",
        "last_name": "Anderson",
        "date_of_birth": date(1985, 3, 15),
        "email": "james.anderson@email.com",
        "phone": "555-0101",
        "address": "123 Oak Street, Springfield, IL 62701",
        "blood_type": "A+",
        "status": PatientStatus.ACTIVE,
        "allergies": "Penicillin",
        "conditions": "Hypertension",
        "last_visit": datetime(2026, 3, 28, 10, 30, tzinfo=timezone.utc),
    },
    {
        "first_name": "Maria",
        "last_name": "Garcia",
        "date_of_birth": date(1990, 7, 22),
        "email": "maria.garcia@email.com",
        "phone": "555-0102",
        "address": "456 Elm Avenue, Portland, OR 97201",
        "blood_type": "O-",
        "status": PatientStatus.ACTIVE,
        "allergies": "Sulfa drugs, Latex",
        "conditions": "Type 2 Diabetes",
        "last_visit": datetime(2026, 3, 15, 14, 0, tzinfo=timezone.utc),
    },
    {
        "first_name": "Robert",
        "last_name": "Chen",
        "date_of_birth": date(1978, 11, 3),
        "email": "robert.chen@email.com",
        "phone": "555-0103",
        "address": "789 Pine Road, Austin, TX 78701",
        "blood_type": "B+",
        "status": PatientStatus.CRITICAL,
        "allergies": "None",
        "conditions": "Chronic kidney disease, Hypertension",
        "last_visit": datetime(2026, 4, 1, 9, 0, tzinfo=timezone.utc),
    },
    {
        "first_name": "Sarah",
        "last_name": "Williams",
        "date_of_birth": date(1995, 1, 30),
        "email": "sarah.williams@email.com",
        "phone": "555-0104",
        "address": "321 Maple Drive, Denver, CO 80201",
        "blood_type": "AB+",
        "status": PatientStatus.ACTIVE,
        "allergies": "Aspirin",
        "conditions": "Asthma",
        "last_visit": datetime(2026, 2, 20, 11, 15, tzinfo=timezone.utc),
    },
    {
        "first_name": "Michael",
        "last_name": "Johnson",
        "date_of_birth": date(1968, 5, 12),
        "email": "michael.johnson@email.com",
        "phone": "555-0105",
        "address": "654 Cedar Lane, Seattle, WA 98101",
        "blood_type": "A-",
        "status": PatientStatus.INACTIVE,
        "allergies": "Codeine, Ibuprofen",
        "conditions": "Osteoarthritis",
        "last_visit": datetime(2025, 11, 5, 16, 0, tzinfo=timezone.utc),
    },
    {
        "first_name": "Emily",
        "last_name": "Davis",
        "date_of_birth": date(2000, 9, 18),
        "email": "emily.davis@email.com",
        "phone": "555-0106",
        "address": "987 Birch Court, Miami, FL 33101",
        "blood_type": "O+",
        "status": PatientStatus.ACTIVE,
        "allergies": "None",
        "conditions": "None",
        "last_visit": datetime(2026, 3, 10, 9, 30, tzinfo=timezone.utc),
    },
    {
        "first_name": "David",
        "last_name": "Martinez",
        "date_of_birth": date(1972, 12, 5),
        "email": "david.martinez@email.com",
        "phone": "555-0107",
        "address": "147 Willow Way, Chicago, IL 60601",
        "blood_type": "B-",
        "status": PatientStatus.CRITICAL,
        "allergies": "Morphine",
        "conditions": "Congestive heart failure, Atrial fibrillation",
        "last_visit": datetime(2026, 4, 3, 8, 0, tzinfo=timezone.utc),
    },
    {
        "first_name": "Jennifer",
        "last_name": "Brown",
        "date_of_birth": date(1988, 4, 25),
        "email": "jennifer.brown@email.com",
        "phone": "555-0108",
        "address": "258 Spruce Boulevard, Boston, MA 02101",
        "blood_type": "A+",
        "status": PatientStatus.ACTIVE,
        "allergies": "Shellfish",
        "conditions": "Migraine, Anxiety disorder",
        "last_visit": datetime(2026, 3, 22, 13, 0, tzinfo=timezone.utc),
    },
    {
        "first_name": "William",
        "last_name": "Taylor",
        "date_of_birth": date(1955, 8, 9),
        "email": "william.taylor@email.com",
        "phone": "555-0109",
        "address": "369 Ash Street, Philadelphia, PA 19101",
        "blood_type": "AB-",
        "status": PatientStatus.ACTIVE,
        "allergies": "Penicillin, Sulfa drugs",
        "conditions": "Type 1 Diabetes, Neuropathy",
        "last_visit": datetime(2026, 3, 5, 10, 0, tzinfo=timezone.utc),
    },
    {
        "first_name": "Jessica",
        "last_name": "Lee",
        "date_of_birth": date(1993, 6, 14),
        "email": "jessica.lee@email.com",
        "phone": "555-0110",
        "address": "741 Poplar Avenue, San Diego, CA 92101",
        "blood_type": "O+",
        "status": PatientStatus.ACTIVE,
        "allergies": "None",
        "conditions": "GERD",
        "last_visit": datetime(2026, 1, 18, 15, 30, tzinfo=timezone.utc),
    },
    {
        "first_name": "Daniel",
        "last_name": "Wilson",
        "date_of_birth": date(1982, 2, 28),
        "email": "daniel.wilson@email.com",
        "phone": "555-0111",
        "address": "852 Hickory Lane, Nashville, TN 37201",
        "blood_type": "A+",
        "status": PatientStatus.INACTIVE,
        "allergies": "Latex",
        "conditions": "Depression",
        "last_visit": datetime(2025, 9, 12, 11, 0, tzinfo=timezone.utc),
    },
    {
        "first_name": "Amanda",
        "last_name": "Moore",
        "date_of_birth": date(1997, 10, 7),
        "email": "amanda.moore@email.com",
        "phone": "555-0112",
        "address": "963 Chestnut Road, Atlanta, GA 30301",
        "blood_type": "B+",
        "status": PatientStatus.ACTIVE,
        "allergies": "Peanuts",
        "conditions": "Eczema, Seasonal allergies",
        "last_visit": datetime(2026, 3, 30, 14, 45, tzinfo=timezone.utc),
    },
    {
        "first_name": "Christopher",
        "last_name": "Thomas",
        "date_of_birth": date(1965, 7, 19),
        "email": "christopher.thomas@email.com",
        "phone": "555-0113",
        "address": "174 Sycamore Drive, Phoenix, AZ 85001",
        "blood_type": "O-",
        "status": PatientStatus.CRITICAL,
        "allergies": "Contrast dye",
        "conditions": "COPD, Lung cancer",
        "last_visit": datetime(2026, 4, 2, 10, 0, tzinfo=timezone.utc),
    },
    {
        "first_name": "Ashley",
        "last_name": "Jackson",
        "date_of_birth": date(1991, 3, 2),
        "email": "ashley.jackson@email.com",
        "phone": "555-0114",
        "address": "285 Magnolia Court, Minneapolis, MN 55401",
        "blood_type": "A-",
        "status": PatientStatus.ACTIVE,
        "allergies": "None",
        "conditions": "Hypothyroidism",
        "last_visit": datetime(2026, 2, 28, 9, 15, tzinfo=timezone.utc),
    },
    {
        "first_name": "Matthew",
        "last_name": "White",
        "date_of_birth": date(1975, 11, 23),
        "email": "matthew.white@email.com",
        "phone": "555-0115",
        "address": "396 Dogwood Street, Detroit, MI 48201",
        "blood_type": "AB+",
        "status": PatientStatus.ACTIVE,
        "allergies": "Erythromycin",
        "conditions": "Gout, Hyperlipidemia",
        "last_visit": datetime(2026, 3, 18, 11, 30, tzinfo=timezone.utc),
    },
    {
        "first_name": "Sophia",
        "last_name": "Harris",
        "date_of_birth": date(2001, 5, 11),
        "email": "sophia.harris@email.com",
        "phone": "555-0116",
        "address": "507 Juniper Way, San Francisco, CA 94101",
        "blood_type": "O+",
        "status": PatientStatus.ACTIVE,
        "allergies": "None",
        "conditions": "Iron deficiency anemia",
        "last_visit": datetime(2026, 3, 25, 16, 0, tzinfo=timezone.utc),
    },
    {
        "first_name": "Andrew",
        "last_name": "Clark",
        "date_of_birth": date(1960, 9, 30),
        "email": "andrew.clark@email.com",
        "phone": "555-0117",
        "address": "618 Redwood Boulevard, Dallas, TX 75201",
        "blood_type": "B+",
        "status": PatientStatus.INACTIVE,
        "allergies": "ACE inhibitors",
        "conditions": "Benign prostatic hyperplasia",
        "last_visit": datetime(2025, 8, 20, 10, 0, tzinfo=timezone.utc),
    },
    {
        "first_name": "Olivia",
        "last_name": "Lewis",
        "date_of_birth": date(1986, 1, 16),
        "email": "olivia.lewis@email.com",
        "phone": "555-0118",
        "address": "729 Cypress Avenue, Raleigh, NC 27601",
        "blood_type": "A+",
        "status": PatientStatus.ACTIVE,
        "allergies": "Gluten",
        "conditions": "Celiac disease",
        "last_visit": datetime(2026, 3, 12, 13, 30, tzinfo=timezone.utc),
    },
    {
        "first_name": "Kevin",
        "last_name": "Robinson",
        "date_of_birth": date(1980, 4, 8),
        "email": "kevin.robinson@email.com",
        "phone": "555-0119",
        "address": "840 Palm Street, Las Vegas, NV 89101",
        "blood_type": "O-",
        "status": PatientStatus.ACTIVE,
        "allergies": "Amoxicillin",
        "conditions": "Sleep apnea, Obesity",
        "last_visit": datetime(2026, 3, 8, 10, 45, tzinfo=timezone.utc),
    },
    {
        "first_name": "Rachel",
        "last_name": "Walker",
        "date_of_birth": date(1998, 8, 21),
        "email": "rachel.walker@email.com",
        "phone": "555-0120",
        "address": "951 Hawthorn Drive, Portland, ME 04101",
        "blood_type": "AB+",
        "status": PatientStatus.ACTIVE,
        "allergies": "Bee stings",
        "conditions": "None",
        "last_visit": datetime(2026, 4, 4, 14, 0, tzinfo=timezone.utc),
    },
]

SEED_NOTES = [
    {"patient_index": 0, "content": "Patient presents with elevated blood pressure 150/95. Adjusted lisinopril dosage to 20mg daily. Follow-up in 2 weeks."},
    {"patient_index": 0, "content": "Blood pressure improved to 135/85. Continue current medication. Recommended dietary changes and exercise."},
    {"patient_index": 1, "content": "HbA1c level at 7.2%. Metformin 500mg twice daily continued. Discussed meal planning and glucose monitoring."},
    {"patient_index": 2, "content": "Creatinine levels elevated at 3.1 mg/dL. GFR declining. Referred to nephrology for dialysis evaluation."},
    {"patient_index": 2, "content": "Nephrology consult completed. Scheduled for fistula placement. Blood pressure management critical."},
    {"patient_index": 3, "content": "Asthma well-controlled with current inhaler regimen. Peak flow readings stable. Annual flu vaccine administered."},
    {"patient_index": 6, "content": "Echocardiogram shows EF at 30%. Increased furosemide to 40mg. Patient experiencing dyspnea on exertion."},
    {"patient_index": 6, "content": "Added spironolactone 25mg. Weight stable. Patient reports improved breathing with medication adjustment."},
    {"patient_index": 7, "content": "Migraine frequency reduced to 2/month with sumatriptan. Anxiety managed with CBT. No medication changes."},
    {"patient_index": 8, "content": "Insulin pump settings adjusted. Neuropathy symptoms managed with gabapentin 300mg TID. Foot exam normal."},
    {"patient_index": 12, "content": "CT scan shows progression of right upper lobe mass. Oncology recommends starting immunotherapy. Patient consented."},
    {"patient_index": 12, "content": "First cycle of immunotherapy completed. Mild fatigue reported. No significant adverse reactions. COPD stable with current inhalers."},
]


async def seed_database(session: AsyncSession) -> None:
    result = await session.execute(select(Patient).limit(1))
    if result.scalar_one_or_none() is not None:
        return

    patients = []
    for data in SEED_PATIENTS:
        patient = Patient(**data)
        session.add(patient)
        patients.append(patient)

    await session.flush()

    for note_data in SEED_NOTES:
        patient = patients[note_data["patient_index"]]
        note = Note(patient_id=patient.id, content=note_data["content"])
        session.add(note)

    await session.commit()
